version: '3.8'

networks:
  backend:
    driver: bridge

services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    network_mode: host
    environment:
      - LOG_LEVEL=info
      - GUACD_SSL=false
    volumes:
      - ./drive:/drive
      - ./recordings:/recordings
    command: ["-L", "info"]

  guacamole:
    build:
      context: .
      dockerfile: Dockerfile.x64
    container_name: guacamole
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - backend
    ports:
      # Port f√ºr externen Zugriff vom Server
      - "8080:8080"
    environment:
      - GUACD_HOSTNAME=172.17.0.1
      - GUACD_PORT=4822
    depends_on:
      - guacd
